# -*- coding: utf-8 -*-
"""DataStructures.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ysYonCwaLXx05V3LSoieB5acrlOLSKgM
"""

print("Task 1: Tuple Operations")

city_tuple = ("Chennai", "Delhi", "Kolkata", "Pune", "Jaipur")


a, b, c, d, e = city_tuple

print(a)
print(b)
print(c)
print(d)
print(e)


try:
    city_tuple[0] = "Goa"
except Exception as error:
    print("Cannot update tuple elements:", error)

print("\n")



print("Task 2: Set Operations")

python_students = {"Rahul", "Sneha", "Arjun", "Meena"}
sql_students = {"Arjun", "Meena", "Kiran", "Anita"}

print("All students (Union):", python_students.union(sql_students))
print("Common students (Intersection):", python_students.intersection(sql_students))
print("Only Python students:", python_students.difference(sql_students))

print("\n")



print("Task 3: ASCII Conversion")

numbers = [70, 71, 72, 73, 74]

for num in numbers:
    char = chr(num)
    print(num, "corresponds to", char)

print("ASCII code of 'Z' is:", ord('Z'))

print("\n")



print("Task 4: Running System Command")

import subprocess

output = subprocess.run("whoami", capture_output=True, text=True, shell=True)

print("Logged in user:", output.stdout.strip())