# -*- coding: utf-8 -*-
"""for_loop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1toLxpaO3-IbQ4Zk_s_ZMq_KFA4ffmN55
"""

#Task 1:



for num in range(1, 6):

  print(num)



#Task 2:



for num in range(1, 11, 2):

  print(num)



#Task 3:



for i in range(3):

  for j in range(2):

    print(i, j)



#Task 4:



for num in range(1, 8):

  if num == 5:

    break

  print(num)