# -*- coding: utf-8 -*-
"""Functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zFqvznUPMDsnWGRFmlP5vqyKlId5l3Gl
"""

def calculate_total(scores):
    """
    Returns the sum of all values in the scores list.
    """
    total_value = 0
    for num in scores:
        total_value += num
    return total_value


def calculate_average(scores):
    """
    Uses calculate_total to find and return the average score.
    """
    total_value = calculate_total(scores)
    avg_value = total_value / len(scores)
    return avg_value


def get_grade(avg):
    """
    Determines grade based on average score.
    """
    if avg > 90:
        return "A"
    elif avg > 75:
        return "B"
    else:
        return "C"


def display_report(scores):
    """
    Prints total marks, average, and grade.
    """
    total_value = calculate_total(scores)
    avg_value = calculate_average(scores)
    grade_value = get_grade(avg_value)

    print("Total:", total_value)
    print("Average:", avg_value)
    print("Grade:", grade_value)



data = [88, 76, 95, 60, 82]
display_report(data)