# -*- coding: utf-8 -*-
"""JSON.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17zrKw-20fEvaOYsaNTkFRNY-qG9D7XNG
"""

import json


student_info = {
    "name": "Anil",
    "age": 21,
    "passed": True,
    "marks": [70, 85, 92],
    "address": {
        "city": "Vijayawada",
        "pincode": 520001
    }
}


student_json = json.dumps(student_info, indent=4)

print("Task 1 Result:")
print(student_json)



data = json.loads(student_json)

print("\nTask 2 Result:")
print("Student Name:", data["name"])
print("Second Mark:", data["marks"][1])
print("City:", data["address"]["city"])



bad_json = '{ name: "Raj", "score": 88, "active": true, }'




correct_json = '{ "name": "Raj", "score": 88, "active": true }'


fixed_data = json.loads(correct_json)

print("\nTask 3 Result:")
print(fixed_data)



product_list = [
    {"product_name": "Phone", "price": 20000, "in_stock": True},
    {"product_name": "Charger", "price": 800, "in_stock": True},
    {"product_name": "Earphones", "price": 1200, "in_stock": False}
]


products_json = json.dumps(product_list, indent=2)

print("\nTask 4 Result:")
print(products_json)