# -*- coding: utf-8 -*-
"""Numerical Computing with NumPy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14QZmg50rG9x4LWYbUGSl3eEh6EGQfjc3
"""

import numpy as np

# Task 1: Generate and Inspect Dataset

np.random.seed(42)  # ensures reproducible results

# Pool of names
name_pool = ["Alice", "Bob", "Charlie", "David", "Eva"]

# Randomly assign names to 10 students
student_names = np.random.choice(name_pool, size=10)

# Ages between 15 and 18
student_ages = np.random.randint(15, 19, size=10)

# Marks between 40 and 100 for three subjects
math_scores = np.random.randint(40, 101, size=10)
science_scores = np.random.randint(40, 101, size=10)
english_scores = np.random.randint(40, 101, size=10)

# Combine subject marks into one array
marks_array = np.column_stack((math_scores, science_scores, english_scores))

print("Marks array shape:", marks_array.shape)
print("Marks array dtype:", marks_array.dtype)


# Task 2: Reshape and Slice

reshaped_marks = marks_array.reshape(2, 5, 3)
print("\nReshaped marks array (2, 5, 3):")
print(reshaped_marks)

# Slice: first five students, only maths and science
subset_marks = marks_array[:5, :2]
print("\nFirst five students - Maths & Science marks:")
print(subset_marks)

# Comment:
# Shape (2, 5, 3) means the 10 students are split into 2 groups,
# each group has 5 students, and each student has 3 subject scores.



# Task 3: Save Records to a File

with open("student_records.txt", "w") as file:
    for i in range(10):
        record = f"{student_names[i]} | {student_ages[i]} | {math_scores[i]} | {science_scores[i]} | {english_scores[i]}\n"
        file.write(record)

print("\nRecords successfully written to student_records.txt.")

# Verify by reading back
with open("student_records.txt", "r") as file:
    content = file.readlines()

print("\nContents of student_records.txt:")
for line in content:
    print(line.strip())