# -*- coding: utf-8 -*-
"""numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1azcyaeFwyWsG7h4W6_rIMfq6ZcfZ2TP3
"""

import numpy as np

# -------------------------
# Task 1: Writing data to a file
# -------------------------
# Create the file and write five warehouse package counts, one per line.
with open("warehouse_data.txt", "w") as file:
    file.write("120\n")
    file.write("85\n")
    file.write("200\n")
    file.write("95\n")
    file.write("150\n")

# Note:
# If we used 'a' (append mode) instead of 'w' (write mode) on a second run,
# the new values would be added after the old ones. That means the file would
# keep growing with repeated runs, instead of replacing the old content.


# -------------------------
# Task 2: Reading the file
# -------------------------
# Open the file in read mode and collect all lines.
with open("warehouse_data.txt", "r") as file:
    lines = file.readlines()   # returns a list of all lines
    cleaned_values = [line.strip() for line in lines]  # remove newline characters

print("Values read from file:")
for value in cleaned_values:
    print(value)

# Note:
# I chose readlines() because it directly gives a list of all lines.
# read() would give one long string, and readline() only one line at a time.
# For this task, readlines() makes it easier to process everything at once.


# -------------------------
# Task 3: NumPy array and statistics
# -------------------------
# Convert the list of strings into integers and build a NumPy array.
data = np.array(cleaned_values, dtype=int)

print("\nNumPy Array:", data)
print("dtype:", data.dtype)
print("shape:", data.shape)
print("size:", data.size)

# Basic statistics
print("Sum:", np.sum(data))
print("Maximum:", np.max(data))
print("Minimum:", np.min(data))

# Note:
# If one of the file entries were a word like "error" instead of a number,
# NumPy would not be able to cast everything to integers.
# In that case, the array would fall back to dtype=object or dtype=str,
# meaning the elements would be treated as strings rather than numbers.