# -*- coding: utf-8 -*-
"""python_basics_<Devi_Ginjala>.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kPG5JL4SvSnHohKiZtKrM6nPqkNV3h2D
"""

#Task 1:

name = "joy"

age = 24

height = 5.3

is_student = True

print(name , age , height , is_student)



#Task 2:

print(f"Name: {name} | Age: {age} | Height: {height} | Student: {is_student}")



#Task 3:

age_in_months=age*12

age_in_days=age*365

remainder=age%7

age_square=age**2


#Task 4

print("Age in months:", age_in_months)

print("Age in days:", age_in_days)

print("Remainder when age divided by 7:", remainder)

print("Age squared:", age_square)