# -*- coding: utf-8 -*-
"""TheatreBookingSystem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IK6NWczx3jkBTopV3I9sz2zaH71kTsUU
"""

capacity = 350
available = capacity

successful_bookings = 0
total_tickets = 0
failed_bookings = 0

while available > 0:
    print("\nSeats left:", available)

    count = int(input("How many tickets do you want? (0 to stop): "))


    if count == 0:
        break


    if count < 1 or count > 15:
        print("Invalid number of tickets (Allowed: 1 to 15)")
        continue


    if count > available:
        print("Booking failed - insufficient seats")
        failed_bookings += 1
        continue

    is_allowed = True


    for person in range(1, count + 1):
        age = int(input(f"Enter age for person {person}: "))

        if age < 12:
            is_allowed = False
            continue   # skip but continue loop


    if not is_allowed:
        print("Booking failed - age restriction")
        failed_bookings += 1
        continue


    print(f"Booking successful for {count} tickets")

    successful_bookings += 1
    total_tickets += count
    available -= count


    if available == 0:
        print("No more seats available")
        break



print("\n===== SUMMARY =====")
print("Successful bookings:", successful_bookings)
print("Tickets sold:", total_tickets)
print("Rejected bookings:", failed_bookings)
print("Seats remaining:", available)

